export const bulkImportFields = {
  employees: [
    "full_name",
    "email",
    "phone",
    "department",
    "job_title",
    "employment_status",
    "manager_name",
    "approval_level",
  ],
  incidents: [
    "title",
    "incident_type",
    "site",
    "department",
    "location",
    "occurred_at",
    "severity",
    "description",
    "immediate_action",
    "persons_involved",
    "responsible_person_name",
    "action_due_date",
  ],
  hazards: [
    "site",
    "department",
    "location",
    "description",
    "likelihood",
    "severity",
    "existing_controls",
    "additional_controls",
    "owner_name",
  ],
  observations: [
    "observation_type",
    "site",
    "department",
    "location",
    "description",
    "immediate_response",
    "observed_at",
    "supervisor_name",
  ],
  near_misses: [
    "title",
    "site",
    "department",
    "location",
    "occurred_at",
    "description",
    "potential_severity",
    "immediate_controls",
    "responsible_person_name",
    "action_due_date",
  ],
  risks: [
    "activity",
    "site",
    "department",
    "category",
    "hazard",
    "consequence",
    "people_exposed",
    "existing_controls",
    "additional_controls",
    "likelihood",
    "severity",
    "residual_likelihood",
    "residual_severity",
    "owner_name",
    "review_date",
  ],
  audits: [
    "title",
    "audit_type",
    "site",
    "department",
    "area",
    "scope",
    "lead_auditor",
    "audit_team",
    "scheduled_on",
  ],
  capa: [
    "title",
    "action_type",
    "source_type",
    "source_reference",
    "owner_name",
    "due_date",
    "priority",
    "preventive_action",
  ],
  inspections: [
    "title",
    "inspection_type",
    "site",
    "department",
    "area",
    "scheduled_on",
    "inspector_name",
    "summary",
  ],
  training: [
    "employee_name",
    "course_name",
    "provider",
    "completed_on",
    "expires_on",
    "certificate_reference",
    "status",
    "notes",
  ],
  competencies: [
    "employee_name",
    "competency_name",
    "required_level",
    "current_level",
    "assessor",
    "assessed_on",
    "expires_on",
    "evidence",
  ],
  objectives: [
    "objective",
    "kpi",
    "baseline",
    "target",
    "current_performance",
    "direction",
    "owner_name",
    "review_date",
    "notes",
  ],
  legal: [
    "legal_obligation",
    "authority",
    "category",
    "compliance_status",
    "review_date",
    "evidence",
    "owner_name",
  ],
  contractors: [
    "company_name",
    "contact_person",
    "contact_email",
    "contact_phone",
    "scope_of_work",
    "approval_status",
    "insurance_provider",
    "insurance_expiry",
    "permit_reference",
    "permit_expiry",
    "hse_score",
    "owner_name",
  ],
  environment: [
    "activity",
    "aspect",
    "impact",
    "condition",
    "likelihood",
    "severity",
    "existing_controls",
    "additional_controls",
    "review_date",
    "owner_name",
  ],
  ppe: [
    "employee_name",
    "ppe_item",
    "serial_number",
    "quantity",
    "issued_on",
    "expected_replacement_on",
    "condition",
    "issued_by_name",
    "notes",
  ],
  documents: [
    "document_number",
    "title",
    "document_type",
    "current_version",
    "review_date",
    "owner_name",
  ],
  reviews: [
    "period_start",
    "period_end",
    "meeting_date",
    "attendees",
    "executive_summary",
    "decisions",
    "chairperson_name",
  ],
} as const;

export type BulkImportModule = keyof typeof bulkImportFields;

/**
 * Map of friendly "*_name" CSV columns to the underlying database UUID columns
 * they resolve to. The server looks up the employee by full_name and substitutes
 * the matching id before insert.
 */
export const employeeNameFieldMap: Record<string, string> = {
  manager_name: "manager_employee_id",
  responsible_person_name: "responsible_person_id",
  owner_name: "owner_id",
  supervisor_name: "supervisor_id",
  inspector_name: "inspector_id",
  employee_name: "employee_id",
  issued_by_name: "issued_by",
  chairperson_name: "chairperson_id",
};
