CREATE TABLE public.user_module_permissions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, module text NOT NULL CHECK (module ~ '^[a-z][a-z0-9_]{1,63}$'), can_view boolean NOT NULL DEFAULT true, can_create boolean NOT NULL DEFAULT false, can_edit boolean NOT NULL DEFAULT false, can_delete boolean NOT NULL DEFAULT false, can_approve boolean NOT NULL DEFAULT false, can_export boolean NOT NULL DEFAULT true, granted_by uuid, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE (user_id, module));
GRANT SELECT, INSERT, UPDATE, DELETE ON public.user_module_permissions TO authenticated; GRANT ALL ON public.user_module_permissions TO service_role; ALTER TABLE public.user_module_permissions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users view own module permissions" ON public.user_module_permissions FOR SELECT TO authenticated USING (user_id = auth.uid() OR public.has_role(auth.uid(), 'admin'));
CREATE POLICY "Admins manage module permissions" ON public.user_module_permissions FOR ALL TO authenticated USING (public.has_role(auth.uid(), 'admin')) WITH CHECK (public.has_role(auth.uid(), 'admin'));
CREATE TRIGGER set_user_module_permissions_updated_at BEFORE UPDATE ON public.user_module_permissions FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.evidence_attachments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), module text NOT NULL CHECK (module IN ('incidents','hazards','observations','near_misses','environment','audits','inspections','risks','capa','contractors')), record_id uuid NOT NULL, storage_path text NOT NULL UNIQUE CHECK (storage_path ~ '^[0-9a-f-]{36}/[a-z_]+/[0-9a-f-]{36}/[0-9a-f-]{36}\.(jpg|jpeg|png|webp|pdf)$'), file_name text NOT NULL CHECK (char_length(file_name) BETWEEN 1 AND 240), mime_type text NOT NULL CHECK (mime_type IN ('image/jpeg','image/png','image/webp','application/pdf')), file_size integer NOT NULL CHECK (file_size BETWEEN 1 AND 10485760), caption text CHECK (char_length(caption) <= 1000), uploaded_by uuid NOT NULL DEFAULT auth.uid(), created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT, INSERT, DELETE ON public.evidence_attachments TO authenticated; GRANT ALL ON public.evidence_attachments TO service_role; ALTER TABLE public.evidence_attachments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Authenticated users view evidence metadata" ON public.evidence_attachments FOR SELECT TO authenticated USING (true);
CREATE POLICY "Users add own evidence metadata" ON public.evidence_attachments FOR INSERT TO authenticated WITH CHECK (uploaded_by = auth.uid());
CREATE POLICY "Owners and managers remove evidence metadata" ON public.evidence_attachments FOR DELETE TO authenticated USING (uploaded_by = auth.uid() OR public.has_role(auth.uid(), 'admin') OR public.has_role(auth.uid(), 'hr_manager') OR public.has_role(auth.uid(), 'hse_manager') OR public.has_role(auth.uid(), 'hse_coordinator'));

CREATE TABLE public.inspection_reports (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), inspection_id uuid NOT NULL REFERENCES public.inspections(id) ON DELETE CASCADE, version integer NOT NULL DEFAULT 1 CHECK (version > 0), executive_summary text NOT NULL CHECK (char_length(executive_summary) BETWEEN 1 AND 12000), findings text NOT NULL CHECK (char_length(findings) BETWEEN 1 AND 20000), recommendations text NOT NULL CHECK (char_length(recommendations) BETWEEN 1 AND 20000), status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','approved','superseded')), generated_by uuid NOT NULL DEFAULT auth.uid(), approved_by uuid, approved_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE (inspection_id, version));
GRANT SELECT, INSERT, UPDATE, DELETE ON public.inspection_reports TO authenticated; GRANT ALL ON public.inspection_reports TO service_role; ALTER TABLE public.inspection_reports ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Authenticated users view inspection reports" ON public.inspection_reports FOR SELECT TO authenticated USING (true);
CREATE POLICY "Inspection managers create reports" ON public.inspection_reports FOR INSERT TO authenticated WITH CHECK (generated_by = auth.uid() AND (public.has_role(auth.uid(), 'admin') OR public.has_role(auth.uid(), 'hr_manager') OR public.has_role(auth.uid(), 'hse_manager') OR public.has_role(auth.uid(), 'hse_coordinator') OR public.has_role(auth.uid(), 'supervisor')));
CREATE POLICY "Inspection managers update reports" ON public.inspection_reports FOR UPDATE TO authenticated USING (public.has_role(auth.uid(), 'admin') OR public.has_role(auth.uid(), 'hr_manager') OR public.has_role(auth.uid(), 'hse_manager') OR public.has_role(auth.uid(), 'hse_coordinator') OR public.has_role(auth.uid(), 'supervisor')) WITH CHECK (public.has_role(auth.uid(), 'admin') OR public.has_role(auth.uid(), 'hr_manager') OR public.has_role(auth.uid(), 'hse_manager') OR public.has_role(auth.uid(), 'hse_coordinator') OR public.has_role(auth.uid(), 'supervisor'));
CREATE POLICY "Admins delete draft inspection reports" ON public.inspection_reports FOR DELETE TO authenticated USING (status = 'draft' AND public.has_role(auth.uid(), 'admin'));
CREATE TRIGGER set_inspection_reports_updated_at BEFORE UPDATE ON public.inspection_reports FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.contractor_risk_assessments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), contractor_id uuid NOT NULL REFERENCES public.contractors(id) ON DELETE CASCADE, reference text NOT NULL UNIQUE, task_description text NOT NULL CHECK (char_length(task_description) BETWEEN 3 AND 5000), hazards text NOT NULL CHECK (char_length(hazards) BETWEEN 3 AND 12000), controls text NOT NULL CHECK (char_length(controls) BETWEEN 3 AND 12000), initial_risk_score integer NOT NULL CHECK (initial_risk_score BETWEEN 1 AND 25), residual_risk_score integer NOT NULL CHECK (residual_risk_score BETWEEN 1 AND 25), status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','submitted','approved','rejected','expired')), assessed_by uuid NOT NULL DEFAULT auth.uid(), approved_by uuid, approved_at timestamptz, valid_until date, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT, INSERT, UPDATE, DELETE ON public.contractor_risk_assessments TO authenticated; GRANT ALL ON public.contractor_risk_assessments TO service_role; ALTER TABLE public.contractor_risk_assessments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Authenticated users view contractor assessments" ON public.contractor_risk_assessments FOR SELECT TO authenticated USING (true);
CREATE POLICY "Authorized staff create contractor assessments" ON public.contractor_risk_assessments FOR INSERT TO authenticated WITH CHECK (assessed_by = auth.uid() AND (public.has_role(auth.uid(), 'admin') OR public.has_role(auth.uid(), 'hr_manager') OR public.has_role(auth.uid(), 'hse_manager') OR public.has_role(auth.uid(), 'hse_coordinator') OR public.has_role(auth.uid(), 'supervisor')));
CREATE POLICY "Authorized managers update contractor assessments" ON public.contractor_risk_assessments FOR UPDATE TO authenticated USING (public.has_role(auth.uid(), 'admin') OR public.has_role(auth.uid(), 'hr_manager') OR public.has_role(auth.uid(), 'hse_manager')) WITH CHECK (public.has_role(auth.uid(), 'admin') OR public.has_role(auth.uid(), 'hr_manager') OR public.has_role(auth.uid(), 'hse_manager'));
CREATE POLICY "Admins delete draft contractor assessments" ON public.contractor_risk_assessments FOR DELETE TO authenticated USING (status = 'draft' AND public.has_role(auth.uid(), 'admin'));
CREATE TRIGGER set_contractor_risk_assessments_updated_at BEFORE UPDATE ON public.contractor_risk_assessments FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.permits_to_work (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), contractor_id uuid NOT NULL REFERENCES public.contractors(id) ON DELETE RESTRICT, risk_assessment_id uuid NOT NULL REFERENCES public.contractor_risk_assessments(id) ON DELETE RESTRICT, permit_number text NOT NULL UNIQUE, work_scope text NOT NULL CHECK (char_length(work_scope) BETWEEN 3 AND 5000), work_location text NOT NULL CHECK (char_length(work_location) BETWEEN 2 AND 500), hazards text NOT NULL CHECK (char_length(hazards) BETWEEN 3 AND 12000), controls text NOT NULL CHECK (char_length(controls) BETWEEN 3 AND 12000), workers text CHECK (char_length(workers) <= 5000), valid_from timestamptz NOT NULL, valid_until timestamptz NOT NULL, status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','issued','active','suspended','closed','cancelled')), issued_by uuid, issued_at timestamptz, approved_by uuid, approved_at timestamptz, closure_notes text CHECK (char_length(closure_notes) <= 5000), created_by uuid NOT NULL DEFAULT auth.uid(), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CHECK (valid_until > valid_from));
GRANT SELECT, INSERT, UPDATE, DELETE ON public.permits_to_work TO authenticated; GRANT ALL ON public.permits_to_work TO service_role; ALTER TABLE public.permits_to_work ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Authenticated users view permits" ON public.permits_to_work FOR SELECT TO authenticated USING (true);
CREATE POLICY "Authorized staff draft permits" ON public.permits_to_work FOR INSERT TO authenticated WITH CHECK (created_by = auth.uid() AND (public.has_role(auth.uid(), 'admin') OR public.has_role(auth.uid(), 'hr_manager') OR public.has_role(auth.uid(), 'hse_manager') OR public.has_role(auth.uid(), 'hse_coordinator') OR public.has_role(auth.uid(), 'supervisor')));
CREATE POLICY "Authorized managers issue permits" ON public.permits_to_work FOR UPDATE TO authenticated USING (public.has_role(auth.uid(), 'admin') OR public.has_role(auth.uid(), 'hr_manager') OR public.has_role(auth.uid(), 'hse_manager')) WITH CHECK (public.has_role(auth.uid(), 'admin') OR public.has_role(auth.uid(), 'hr_manager') OR public.has_role(auth.uid(), 'hse_manager'));
CREATE POLICY "Admins delete draft permits" ON public.permits_to_work FOR DELETE TO authenticated USING (status = 'draft' AND public.has_role(auth.uid(), 'admin'));
CREATE TRIGGER set_permits_to_work_updated_at BEFORE UPDATE ON public.permits_to_work FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.company_report_settings (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_name text NOT NULL DEFAULT 'Prosel Limited' CHECK (char_length(company_name) BETWEEN 2 AND 200), letterhead_path text CHECK (letterhead_path IS NULL OR letterhead_path ~ '^letterhead/[0-9a-f-]{36}\.(jpg|jpeg|png|webp|pdf)$'), report_footer text CHECK (char_length(report_footer) <= 1000), default_timezone text NOT NULL DEFAULT 'Africa/Nairobi' CHECK (char_length(default_timezone) BETWEEN 3 AND 80), updated_by uuid, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT, INSERT, UPDATE, DELETE ON public.company_report_settings TO authenticated; GRANT ALL ON public.company_report_settings TO service_role; ALTER TABLE public.company_report_settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Authenticated users view report settings" ON public.company_report_settings FOR SELECT TO authenticated USING (true);
CREATE POLICY "Admins manage report settings" ON public.company_report_settings FOR ALL TO authenticated USING (public.has_role(auth.uid(), 'admin')) WITH CHECK (public.has_role(auth.uid(), 'admin'));
CREATE TRIGGER set_company_report_settings_updated_at BEFORE UPDATE ON public.company_report_settings FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.generated_reports (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), report_number text NOT NULL UNIQUE, module text NOT NULL CHECK (module ~ '^[a-z][a-z0-9_]{1,63}$'), record_id uuid, title text NOT NULL CHECK (char_length(title) BETWEEN 2 AND 300), report_data jsonb NOT NULL DEFAULT '{}'::jsonb, status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','approved','sent','superseded')), generated_by uuid NOT NULL DEFAULT auth.uid(), approved_by uuid, approved_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT, INSERT, UPDATE, DELETE ON public.generated_reports TO authenticated; GRANT ALL ON public.generated_reports TO service_role; ALTER TABLE public.generated_reports ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Authenticated users view generated reports" ON public.generated_reports FOR SELECT TO authenticated USING (true);
CREATE POLICY "Authenticated users create draft reports" ON public.generated_reports FOR INSERT TO authenticated WITH CHECK (generated_by = auth.uid() AND status = 'draft');
CREATE POLICY "Managers approve generated reports" ON public.generated_reports FOR UPDATE TO authenticated USING (generated_by = auth.uid() OR public.has_role(auth.uid(), 'admin') OR public.has_role(auth.uid(), 'hr_manager') OR public.has_role(auth.uid(), 'hse_manager')) WITH CHECK (generated_by = auth.uid() OR public.has_role(auth.uid(), 'admin') OR public.has_role(auth.uid(), 'hr_manager') OR public.has_role(auth.uid(), 'hse_manager'));
CREATE POLICY "Admins delete draft generated reports" ON public.generated_reports FOR DELETE TO authenticated USING (status = 'draft' AND (generated_by = auth.uid() OR public.has_role(auth.uid(), 'admin')));
CREATE TRIGGER set_generated_reports_updated_at BEFORE UPDATE ON public.generated_reports FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.report_subscriptions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), module text NOT NULL CHECK (module ~ '^[a-z][a-z0-9_]{1,63}$'), recipients text[] NOT NULL CHECK (cardinality(recipients) BETWEEN 1 AND 50), cadence text NOT NULL DEFAULT 'weekly' CHECK (cadence IN ('daily','weekly','monthly')), weekday smallint CHECK (weekday BETWEEN 0 AND 6), hour_utc smallint NOT NULL DEFAULT 6 CHECK (hour_utc BETWEEN 0 AND 23), is_active boolean NOT NULL DEFAULT true, next_run_at timestamptz NOT NULL DEFAULT now(), last_run_at timestamptz, created_by uuid NOT NULL DEFAULT auth.uid(), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT, INSERT, UPDATE, DELETE ON public.report_subscriptions TO authenticated; GRANT ALL ON public.report_subscriptions TO service_role; ALTER TABLE public.report_subscriptions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins manage report subscriptions" ON public.report_subscriptions FOR ALL TO authenticated USING (public.has_role(auth.uid(), 'admin')) WITH CHECK (public.has_role(auth.uid(), 'admin'));
CREATE TRIGGER set_report_subscriptions_updated_at BEFORE UPDATE ON public.report_subscriptions FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE POLICY "Authenticated users read HSE evidence files" ON storage.objects FOR SELECT TO authenticated USING (bucket_id = 'hse-evidence');
CREATE POLICY "Authenticated users upload own HSE evidence" ON storage.objects FOR INSERT TO authenticated WITH CHECK (bucket_id = 'hse-evidence' AND (storage.foldername(name))[1] = auth.uid()::text);
CREATE POLICY "Owners and managers remove HSE evidence" ON storage.objects FOR DELETE TO authenticated USING (bucket_id = 'hse-evidence' AND ((storage.foldername(name))[1] = auth.uid()::text OR public.has_role(auth.uid(), 'admin') OR public.has_role(auth.uid(), 'hr_manager') OR public.has_role(auth.uid(), 'hse_manager') OR public.has_role(auth.uid(), 'hse_coordinator')));
CREATE POLICY "Authenticated users read company letterheads" ON storage.objects FOR SELECT TO authenticated USING (bucket_id = 'company-letterheads');
CREATE POLICY "Admins upload company letterheads" ON storage.objects FOR INSERT TO authenticated WITH CHECK (bucket_id = 'company-letterheads' AND public.has_role(auth.uid(), 'admin'));
CREATE POLICY "Admins update company letterheads" ON storage.objects FOR UPDATE TO authenticated USING (bucket_id = 'company-letterheads' AND public.has_role(auth.uid(), 'admin')) WITH CHECK (bucket_id = 'company-letterheads' AND public.has_role(auth.uid(), 'admin'));
CREATE POLICY "Admins remove company letterheads" ON storage.objects FOR DELETE TO authenticated USING (bucket_id = 'company-letterheads' AND public.has_role(auth.uid(), 'admin'));

CREATE INDEX evidence_attachments_record_idx ON public.evidence_attachments(module, record_id); CREATE INDEX inspection_reports_inspection_idx ON public.inspection_reports(inspection_id, version DESC); CREATE INDEX contractor_risk_assessments_contractor_idx ON public.contractor_risk_assessments(contractor_id, status); CREATE INDEX permits_to_work_contractor_idx ON public.permits_to_work(contractor_id, status); CREATE INDEX report_subscriptions_due_idx ON public.report_subscriptions(is_active, next_run_at);