DROP POLICY IF EXISTS "Authorized users create CAPA" ON public.actions;
CREATE POLICY "Authorized users create CAPA" ON public.actions FOR INSERT TO authenticated WITH CHECK (auth.uid() = created_by AND (public.has_module_permission(auth.uid(), 'capa', 'create') OR public.has_module_permission(auth.uid(), 'capa', 'edit')));
DROP POLICY IF EXISTS "Authorized users create audits" ON public.audits;
CREATE POLICY "Authorized users create audits" ON public.audits FOR INSERT TO authenticated WITH CHECK (auth.uid() = created_by AND (public.has_module_permission(auth.uid(), 'audits', 'create') OR public.has_module_permission(auth.uid(), 'audits', 'edit')));
DROP POLICY IF EXISTS "Authorized users create competencies" ON public.competency_records;
CREATE POLICY "Authorized users create competencies" ON public.competency_records FOR INSERT TO authenticated WITH CHECK (auth.uid() = created_by AND (public.has_module_permission(auth.uid(), 'competencies', 'create') OR public.has_module_permission(auth.uid(), 'competencies', 'edit')));
DROP POLICY IF EXISTS "Authorized users create contractors" ON public.contractors;
CREATE POLICY "Authorized users create contractors" ON public.contractors FOR INSERT TO authenticated WITH CHECK (auth.uid() = created_by AND (public.has_module_permission(auth.uid(), 'contractors', 'create') OR public.has_module_permission(auth.uid(), 'contractors', 'edit')));
DROP POLICY IF EXISTS "Authorized users create environmental aspects" ON public.environmental_aspects;
CREATE POLICY "Authorized users create environmental aspects" ON public.environmental_aspects FOR INSERT TO authenticated WITH CHECK (auth.uid() = created_by AND (public.has_module_permission(auth.uid(), 'environment', 'create') OR public.has_module_permission(auth.uid(), 'environment', 'edit')));
DROP POLICY IF EXISTS "Authorized users create hazards" ON public.hazards;
CREATE POLICY "Authorized users create hazards" ON public.hazards FOR INSERT TO authenticated WITH CHECK (auth.uid() = reported_by AND (public.has_module_permission(auth.uid(), 'hazards', 'create') OR public.has_module_permission(auth.uid(), 'hazards', 'edit')));
DROP POLICY IF EXISTS "Authorized users create documents" ON public.hse_documents;
CREATE POLICY "Authorized users create documents" ON public.hse_documents FOR INSERT TO authenticated WITH CHECK (auth.uid() = created_by AND (public.has_module_permission(auth.uid(), 'documents', 'create') OR public.has_module_permission(auth.uid(), 'documents', 'edit')));
DROP POLICY IF EXISTS "Authorized users create objectives" ON public.hse_objectives;
CREATE POLICY "Authorized users create objectives" ON public.hse_objectives FOR INSERT TO authenticated WITH CHECK (auth.uid() = created_by AND (public.has_module_permission(auth.uid(), 'objectives', 'create') OR public.has_module_permission(auth.uid(), 'objectives', 'edit')));
DROP POLICY IF EXISTS "Authorized users create incidents" ON public.incidents;
CREATE POLICY "Authorized users create incidents" ON public.incidents FOR INSERT TO authenticated WITH CHECK (auth.uid() = reported_by AND (public.has_module_permission(auth.uid(), 'incidents', 'create') OR public.has_module_permission(auth.uid(), 'incidents', 'edit')));
DROP POLICY IF EXISTS "Authorized users create inspections" ON public.inspections;
CREATE POLICY "Authorized users create inspections" ON public.inspections FOR INSERT TO authenticated WITH CHECK (auth.uid() = created_by AND (public.has_module_permission(auth.uid(), 'inspections', 'create') OR public.has_module_permission(auth.uid(), 'inspections', 'edit')));
DROP POLICY IF EXISTS "Authorized users create legal requirements" ON public.legal_requirements;
CREATE POLICY "Authorized users create legal requirements" ON public.legal_requirements FOR INSERT TO authenticated WITH CHECK (auth.uid() = created_by AND (public.has_module_permission(auth.uid(), 'legal', 'create') OR public.has_module_permission(auth.uid(), 'legal', 'edit')));
DROP POLICY IF EXISTS "Authorized users create management reviews" ON public.management_reviews;
CREATE POLICY "Authorized users create management reviews" ON public.management_reviews FOR INSERT TO authenticated WITH CHECK (auth.uid() = created_by AND (public.has_module_permission(auth.uid(), 'reviews', 'create') OR public.has_module_permission(auth.uid(), 'reviews', 'edit')));
DROP POLICY IF EXISTS "Authorized users create near misses" ON public.near_misses;
CREATE POLICY "Authorized users create near misses" ON public.near_misses FOR INSERT TO authenticated WITH CHECK (auth.uid() = reported_by AND (public.has_module_permission(auth.uid(), 'near_misses', 'create') OR public.has_module_permission(auth.uid(), 'near_misses', 'edit')));
DROP POLICY IF EXISTS "Authorized users create PPE issuances" ON public.ppe_issuances;
CREATE POLICY "Authorized users create PPE issuances" ON public.ppe_issuances FOR INSERT TO authenticated WITH CHECK (auth.uid() = created_by AND (public.has_module_permission(auth.uid(), 'ppe', 'create') OR public.has_module_permission(auth.uid(), 'ppe', 'edit')));
DROP POLICY IF EXISTS "Authorized users create risks" ON public.risk_assessments;
CREATE POLICY "Authorized users create risks" ON public.risk_assessments FOR INSERT TO authenticated WITH CHECK (auth.uid() = created_by AND (public.has_module_permission(auth.uid(), 'risks', 'create') OR public.has_module_permission(auth.uid(), 'risks', 'edit')));
DROP POLICY IF EXISTS "Authorized users create observations" ON public.safety_observations;
CREATE POLICY "Authorized users create observations" ON public.safety_observations FOR INSERT TO authenticated WITH CHECK (auth.uid() = observed_by AND (public.has_module_permission(auth.uid(), 'observations', 'create') OR public.has_module_permission(auth.uid(), 'observations', 'edit')));
DROP POLICY IF EXISTS "Authorized users create training" ON public.training_records;
CREATE POLICY "Authorized users create training" ON public.training_records FOR INSERT TO authenticated WITH CHECK (auth.uid() = created_by AND (public.has_module_permission(auth.uid(), 'training', 'create') OR public.has_module_permission(auth.uid(), 'training', 'edit')));
DROP POLICY IF EXISTS "Authorized users create employees" ON public.employees;
CREATE POLICY "Authorized users create employees" ON public.employees FOR INSERT TO authenticated WITH CHECK (public.has_module_permission(auth.uid(), 'employees', 'create') OR public.has_module_permission(auth.uid(), 'employees', 'edit'));